export const CANCEL_STATES = [
  'CANCEL_STARTED',
  'FIND_EXISTING_APPOINTMENT',
  'SELECT_APPOINTMENT_IF_MULTIPLE',
  'CONFIRM_CANCEL_REQUEST',
  'CREATE_CANCEL_ACTION_REQUEST',
  'DONE',
] as const;

export const RESCHEDULE_STATES = [
  'RESCHEDULE_STARTED',
  'FIND_EXISTING_APPOINTMENT',
  'SELECT_APPOINTMENT_IF_MULTIPLE',
  'ASK_NEW_DATE',
  'ASK_NEW_TIME',
  'CHECK_NEW_SLOTS',
  'PROPOSE_NEW_SLOTS',
  'HOLD_NEW_SLOT',
  'CONFIRM_RESCHEDULE_REQUEST',
  'CREATE_RESCHEDULE_ACTION_REQUEST',
  'DONE',
] as const;

export const HANDOFF_STATES = [
  'HANDOFF_STARTED',
  'ASK_REASON_OPTIONAL',
  'ASK_NAME_IF_NEEDED',
  'ASK_PHONE_IF_NEEDED',
  'CREATE_CALLBACK_REQUEST',
  'DONE',
] as const;
