export {
  API_ERROR_CODES,
  apiErrorBodySchema,
  apiErrorCodeSchema,
  AppError,
  createRequestId,
  REQUEST_ID_HEADER,
  statusCodeForErrorCode,
  toApiErrorBody,
  type ApiErrorBody,
  type ApiErrorCode,
} from './errors/index';

export {
  apiSuccessBodySchema,
  apiSuccessMetaSchema,
  isApiErrorBody,
  toApiSuccessBody,
  type ApiSuccessBody,
  type ApiSuccessMeta,
} from './api-success';

export {
  authContextSchema,
  canAccessClinic,
  clinicRoleSchema,
  platformRoleSchema,
  type AuthContext,
  type ClinicRole,
  type PlatformRole,
} from './rbac';

export {
  ADAPTER_TOKENS,
  type ActionValidationContext,
  type ActionValidator,
  type AuditLogInput,
  type AuditService,
  type IntentClassifierAdapter,
  type IntentClassifierEntities,
  type IntentClassifierInput,
  type IntentClassifierResult,
  type StateEntityExtractorAdapter,
  type StateEntityExtractorInput,
  type StateEntityExtractorResult,
  type StateRecognizedAs,
  type SideQuestionIntent,
  type MessageSafetyResult,
  type LockService,
  type NotificationProvider,
  type NotificationSendInput,
  type MessagingProvider,
  type MessagingSendInput,
  type ObjectStorageProvider,
  type ObjectStoragePutInput,
  type EnqueueJobInput,
  type QueueJobPayload,
  type QueueService,
  type RateLimitService,
  type SchedulerService,
  type ActiveClinicServiceProfile,
  type ServiceRouterAdapter,
  type ServiceRouterInput,
  type ServiceRouterResult,
  type SttProvider,
  type SttTranscribeInput,
  type TelephonyProvider,
  type TtsProvider,
  type TtsSynthesizeInput,
  type VoiceAdapter,
  type VoiceAdapterIncomingCallInput,
  type VoiceAdapterIncomingCallResult,
  type VoiceCallSessionService,
  type CallRecordingStorage,
  type CallRecordingMetadataInput,
  type CallRecordingMetadataResult,
  type ReceptionistDialogPlannerAdapter,
} from './adapters/index';

export {
  type EmbeddingInput,
  type EmbeddingProvider,
  type EmbeddingResult,
} from './adapters/embedding-provider';

export {
  type KnowledgeSearchInput,
  type KnowledgeSearchProvider,
  type KnowledgeSearchResult,
  type KnowledgeSearchTool,
} from './knowledge/knowledge-search';

export { buildKnowledgeSearchText, type KnowledgeSearchTextInput } from './knowledge/search-text';

export { VOICE_RUNTIME_DEFAULTS, type VoiceRuntimeConfig } from './voice/index';

export * from './jobs/index';

export { DTO_PACKAGE_VERSION } from './dto/index';
export * from './dto/index';

export * from './enums/index';

export {
  API_METHOD_SEMANTICS,
  API_RESOURCE_POLICIES,
  API_ROUTE_PATHS,
  buildClinicRoute,
  isMethodAllowed,
  supportsDisableAction,
  type ApiResourceKey,
  type ApiRouteKey,
  type HttpMethod,
  type ResourceMethodPolicy,
} from './api-client/index';

export {
  MESSAGE_TEMPLATE_KEYS,
  CODE_TEMPLATE_REGISTRY,
  TEMPLATE_LANGUAGES,
  assertTemplateRegistryComplete,
  getCodeTemplateText,
  messageTemplateKeySchema,
  messageTemplateResponseSchema,
  type MessageTemplateKey,
  type MessageTemplateResponse,
  type TemplateLanguageCode,
} from './templates/index';

export {
  BOOKING_FLOW,
  BOOKING_STATES,
  bookingCollectedSchema,
  parseBookingCollected,
  proposedSlotSchema,
  type BookingCollected,
  type BookingState,
  type ProposedSlot,
  type ExtractedBookingFields,
  type TimePreference,
  applyReasonForVisitUpdate,
  buildServiceRouterMemoryCacheKey,
  lookupServiceRouterCache,
  lookupServiceRouterMemoryCache,
  normalizeReasonForRouterCache,
  shouldPersistServiceRouterCache,
  storeServiceRouterCacheEntry,
  storeServiceRouterMemoryCache,
  type ServiceRouterCache,
  type ServiceRouterRouteOutcome,
  enrichExtractedForBookingState,
  hasBookingProgress,
  inferBookingState,
  resumeBookingSession,
} from './booking/index';

export {
  FEE_CLARIFICATION_FLOW,
  KNOWLEDGE_INTENTS,
  STRUCTURED_INFO_INTENTS,
} from './structured-info/index';

export {
  CANCEL_FLOW,
  RESCHEDULE_FLOW,
  HANDOFF_FLOW,
  CANCEL_INTENTS,
  RESCHEDULE_INTENTS,
  HANDOFF_INTENTS,
  parseCancelCollected,
  parseRescheduleCollected,
  parseHandoffCollected,
  type AppointmentCandidate,
  type CancelCollected,
  type RescheduleCollected,
  type HandoffCollected,
} from './lifecycle/index';

export {
  AGENT_INTENTS,
  DEFAULT_INTENT_CONFIDENCE,
  LOW_INTENT_CONFIDENCE,
  LOW_STATE_ENTITY_CONFIDENCE,
  LlmJsonParser,
  classifyIntentMock,
  tryDeterministicIntentClassification,
  routeServiceMock,
  routeServiceFromProfiles,
  parseServiceRouterJson,
  extractProfileTerms,
  buildServiceClarificationQuestion,
  normalizeIntentClassification,
  isActiveFlowClassifierInterrupt,
  hasActiveBookingPrompt,
  ACTIVE_FLOW_CLASSIFIER_INTERRUPTS,
  type NluNormalizationResult,
  attachActivePrompt,
  buildActivePromptSnapshot,
  ACTIVE_PROMPT_KEY,
  BOOKING_INTERRUPT_KEY,
  BOOKING_RESUME_TEMPLATE_BY_STATE,
  RESCHEDULE_RESUME_TEMPLATE_BY_STATE,
  resolveResumeBookingState,
  resolveResumeTemplateKeyForFlow,
  isActiveReceptionistFlow,
  resolveGlobalIntentPolicy,
  staffConfirmTemplateKey,
  preservesCollectedFieldsDuringSideQuestion,
  parseActivePrompt,
  normalizeAppointmentRoutingSource,
  checkQaGates,
  buildNluReviewExportCases,
  buildReviewedExamplesExportCases,
  isEligibleLanguagePackToken,
  proposeLanguagePackAdditionsFromReviewedExamples,
  appendWordsToLanguagePackField,
  languagePackToDbJson,
  DEFAULT_QA_GATE_THRESHOLDS,
  type QaGateCheckResult,
  type ActivePromptSnapshot,
  type ConversationPolicyDecision,
  INTENT_TEMPLATE_MAP,
  templateKeyForIntent,
  type AgentIntent,
  type LlmChatMessage,
  type LlmChatRequest,
  type LlmChatResponse,
  type LlmStreamDelta,
  type LlmStreamHandlers,
  type LlmClient,
  type LlmClientOptions,
  type LlmRequestRuntimeOptions,
  type LlmEvaluationCase,
  type LlmEvaluationRunner,
  type LlmJsonParseResult,
  isActiveStateInterpreterContext,
  resolveInterpreterContext,
  expectedFieldsForState,
  detectMessageSafety,
  buildSafetyIntentClassification,
  isStateEntityYesConfirmation,
  isStateEntityNoRejection,
  resolveTerminalAckTransition,
  resolveTerminalAckOutcome,
  readAwaitingTerminalAck,
  tryDeterministicActiveStateEntity,
  correctActiveStateEntityResult,
  extractActiveReasonForVisit,
  extractActiveExactTime,
  extractActivePreferredDate,
  isActiveAffirmative,
  isActiveDeclining,
  selectOfferedSlot,
  summarizeLlmPath,
  skippedClassifierLlmDebug,
  attachIntentClassifierLlmDebug,
  attachStateEntityLlmDebug,
  buildSarvamLlmDebug,
  deterministicLlmDebug,
  mockLlmDebug,
  extractStateEntitiesMock,
  extractStateEntitiesMockCore,
  getDefaultLanguagePack,
  interpretLanguagePackFastPath,
  resolveContextSensitiveAnswer,
  runActiveStatePreflight,
  languagePackFromDbRow,
  type LanguagePack,
  languagePackLlmDebug,
  buildAgentTrace,
  sanitizeAuditMessagePreview,
  type AgentTrace,
  type CapabilityEvaluationCase,
  type CapabilityEvaluationReport,
  isDeterministicStateEntityResult,
  mapClassificationToBookingFields,
  mergeExtractedBookingFields,
  resolveAvailabilityTargetFromClassification,
  resolveFeeVisitTypeFromClassification,
  resolveTimingScopeFromClassification,
  isProcedureFeeFromClassification,
  type FeeVisitType,
  type TimingScope,
  type AvailabilityTarget,
  parseStateEntityExtractorJson,
  applyContextualStateEntityFallback,
  safeStateEntityFallback,
  resolveLlmLatencyProfile,
  resolveLlmRuntimeSettings,
  llmRuntimeToClientOptions,
  maxTokensForRequest,
  COMPACT_CLASSIFIER_SYSTEM_PROMPT,
  COMPACT_EXTRACTOR_SYSTEM_PROMPT,
  COMPACT_SERVICE_ROUTER_SYSTEM_PROMPT,
  buildCompactClassifierUserPayload,
  buildCompactExtractorUserPayload,
  buildCompactServiceRouterUserPayload,
  isClinicIdentityQuestion,
  messageReferencesClinicName,
  shouldTryKnowledgeBeforeClarify,
  extractSarvamAssistantContent,
  extractSarvamAssistantToolCalls,
  parseLlmToolCalls,
  buildChatCompletionToolsPayload,
  assertValidChatCompletionToolRequest,
  serializeChatCompletionMessages,
  CLINIC_AGENT_TOOLS,
  CLINIC_AGENT_TOOL_NAMES,
  CLINIC_AGENT_SYSTEM_PROMPT,
  RECEPTIONIST_AGENT_SYSTEM_PROMPT,
  RECEPTIONIST_AGENT_SYSTEM_PROMPT_COMPACT,
  RECEPTIONIST_AGENT_SYSTEM_PROMPT_SARVAM,
  buildReceptionistAgentSystemPrompt,
  buildReceptionistAgentSystemPromptCompact,
  buildReceptionistAgentSystemPromptForProvider,
  buildReceptionistAgentSystemPromptSarvam,
  buildReceptionistAgentBookingContext,
  extractAgentBookingFieldPatch,
  shouldSteerBookingReply,
  resolveBookingGuidedReply,
  buildBookingContextForCollected,
  SARVAM_AGENT_MAX_SYSTEM_PROMPT_CHARS,
  isClinicAgentToolName,
  buildSarvamRequestHeaders,
  resolveSarvamAuthModeAttempts,
  normalizeSarvamAuthMode,
  redactSarvamLogPayload,
  parseIntentClassifierJson,
  normalizeIntentClassifierResult,
  unknownIntentClassifierResult,
  resolveCapabilityForIntent,
  normalizeIntentToCapabilityKey,
  capabilityTemplateKeyForIntent,
  shouldRouteToStructuredInfoHandler,
  capabilityUsesApprovedKnowledge,
  isCapabilityLifecycleInterrupt,
  isCapabilityFlowInterrupt,
  capabilityAllowsActiveFlowSideQuestion,
  RECEPTIONIST_CAPABILITY_REGISTRY,
  type ReceptionistCapability,
  type ReceptionistCapabilityKey,
  type CapabilitySourceOfTruth,
  type CapabilityBackendAction,
  parseReceptionistDialogPlan,
  parseReceptionistDialogPlanFromContent,
  buildReceptionistDialogUserPayload,
  unknownSafeFallbackPlan,
  buildClinicCapabilitiesForDialogInput,
  capabilityToIntent,
  attachActiveTask,
  markTaskCompleted,
  parseActiveTask,
  parseSuspendedTask,
  parseLastCompletedTask,
  buildActiveTaskForTemplate,
  shouldPreserveActiveTaskOnTemplate,
  isFinalAssistantTemplate,
  resolveResumePromptTemplateKey,
  shouldOfferRepeatedPromptEscalation,
  incrementRepeatedPromptCount,
  planReceptionistDialogMock,
  RECEPTIONIST_DIALOG_SYSTEM_PROMPT,
  type ReceptionistDialogInput,
  type ReceptionistDialogPlan,
  type ReceptionistConversationTurn,
  type ReceptionistDialogCapability,
  type SarvamAuthMode,
  type SarvamMessagePayload,
  type LlmToolCall,
  type LlmToolDefinition,
  type ClinicAgentToolName,
  type LlmLatencyProfile,
  type LlmRuntimeSettings,
  type LlmInvocationDebug,
} from './agent/index';
