/** Tables required by C04 final schema alignment. */
export const C04_REQUIRED_TABLES = [
  'clinics',
  'clinic_settings',
  'users',
  'clinic_users',
  'clinic_onboarding_checklist',
  'clinic_telephony_settings',
  'doctors',
  'clinic_services',
  'doctor_services',
  'doctor_service_booking_rules',
  'doctor_schedules',
  'clinic_hours',
  'clinic_holidays',
  'clinic_holiday_doctors',
  'doctor_blocked_slots',
  'patients',
  'patient_visits',
  'appointment_slots',
  'slot_holds',
  'appointment_requests',
  'appointment_events',
  'appointment_action_requests',
  'conversation_sessions',
  'conversation_messages',
  'message_idempotency_keys',
  'calls',
  'call_transcripts',
  'callback_requests',
  'emergency_incidents',
  'knowledge_files',
  'clinic_knowledge_base',
  'clinic_knowledge_translations',
  'supported_languages',
  'clinic_languages',
  'message_templates',
  'language_packs',
  'notification_events',
  'audit_logs',
  'subscription_plans',
  'clinic_subscriptions',
  'clinic_usage_monthly',
  'subscription_events',
  'background_jobs',
  'nlu_review_items',
  'reviewed_examples',
] as const;

export const C04_APPOINTMENT_SLOT_COLUMNS = [
  'clinic_id',
  'doctor_id',
  'clinic_service_id',
  'start_time',
  'end_time',
  'capacity_total',
  'status',
  'generated_from_rule_id',
  'generation_batch_id',
  'config_version',
  'created_at',
  'updated_at',
] as const;

export const C04_SLOT_HOLD_COLUMNS = [
  'clinic_id',
  'slot_id',
  'session_id',
  'patient_phone',
  'status',
  'hold_expires_at',
  'created_at',
  'updated_at',
] as const;

export const C04_BOOKING_RULE_COLUMNS = [
  'clinic_id',
  'doctor_id',
  'clinic_service_id',
  'slot_duration_minutes',
  'capacity_per_slot',
  'booking_horizon_days',
  'min_booking_notice_minutes',
  'max_advance_booking_days',
  'manual_edit_cutoff_before_start_minutes',
  'manual_edit_max_shift_minutes',
  'effective_from',
  'effective_to',
  'active',
  'version',
  'created_at',
  'updated_at',
] as const;

export const C04_APPOINTMENT_REQUEST_COLUMNS = [
  'slot_id',
  'slot_hold_id',
  'patient_id',
  'patient_name',
  'patient_phone',
  'doctor_id',
  'clinic_service_id',
  'reason_for_visit',
  'normalized_reason',
  'appointment_start',
  'appointment_end',
  'status',
  'is_followup',
  'followup_of_visit_id',
  'routing_source',
  'source_session_id',
  'replaces_appointment_id',
  'replaced_by_appointment_id',
  'created_at',
  'updated_at',
] as const;

export const C04_ACTION_REQUEST_COLUMNS = [
  'clinic_id',
  'appointment_id',
  'request_type',
  'requested_by',
  'status',
  'requested_new_slot_id',
  'requested_new_date',
  'requested_new_time_preference',
  'reason',
  'source_call_id',
  'source_session_id',
  'created_at',
  'updated_at',
] as const;

export const SEED_CLINIC_ID = '00000000-0000-0000-0000-000000000001';
export const SEED_DOCTOR_WITHOUT_LOGIN_ID = '00000000-0000-0000-0000-000000000201';
