import { QUEUE_NAMES, type QueueName } from './queue-names';

export const JOB_TYPES = {
  SEND_NOTIFICATION: 'SEND_NOTIFICATION',
  EXPIRE_SLOT_HOLDS: 'EXPIRE_SLOT_HOLDS',
  GENERATE_SLOTS: 'GENERATE_SLOTS',
  CLEANUP_EXPIRED_RECORDINGS: 'CLEANUP_EXPIRED_RECORDINGS',
  CLEANUP_EXPIRED_TRANSCRIPTS: 'CLEANUP_EXPIRED_TRANSCRIPTS',
  PARSE_KNOWLEDGE_DOCX: 'PARSE_KNOWLEDGE_DOCX',
  GENERATE_KNOWLEDGE_EMBEDDING: 'GENERATE_KNOWLEDGE_EMBEDDING',
  GENERATE_DAILY_CLINIC_REPORT: 'GENERATE_DAILY_CLINIC_REPORT',
} as const;

export type JobType = (typeof JOB_TYPES)[keyof typeof JOB_TYPES];

export const ALL_JOB_TYPES: readonly JobType[] = Object.values(JOB_TYPES);

export const JOB_QUEUE_MAP: Record<JobType, QueueName> = {
  [JOB_TYPES.SEND_NOTIFICATION]: QUEUE_NAMES.NOTIFICATIONS,
  [JOB_TYPES.EXPIRE_SLOT_HOLDS]: QUEUE_NAMES.SLOT_HOLDS,
  [JOB_TYPES.GENERATE_SLOTS]: QUEUE_NAMES.SLOT_GENERATION,
  [JOB_TYPES.CLEANUP_EXPIRED_RECORDINGS]: QUEUE_NAMES.RECORDINGS_CLEANUP,
  [JOB_TYPES.CLEANUP_EXPIRED_TRANSCRIPTS]: QUEUE_NAMES.TRANSCRIPTS_CLEANUP,
  [JOB_TYPES.PARSE_KNOWLEDGE_DOCX]: QUEUE_NAMES.KNOWLEDGE_PROCESSING,
  [JOB_TYPES.GENERATE_KNOWLEDGE_EMBEDDING]: QUEUE_NAMES.EMBEDDINGS,
  [JOB_TYPES.GENERATE_DAILY_CLINIC_REPORT]: QUEUE_NAMES.DAILY_REPORTS,
};
